In [35]:
import os
states = [12, 9, 9, 9, 6]
class_names = ['len', 'xuong', 'trai', 'phai', 'A','B','nhay','ban']
length = 0
length += len(os.listdir("audio/"))
print(length)

208


In [36]:
import librosa
import numpy as np
import os
import math
from sklearn.cluster import KMeans
import hmmlearn.hmm

def get_mfcc(file_path):
    y, sr = librosa.load(file_path) # read .wav file
    hop_length = math.floor(sr*0.010) # 10ms hop
    win_length = math.floor(sr*0.025) # 25ms frame
    # mfcc is 12 x T matrix
    mfcc = librosa.feature.mfcc(
        y, sr, n_mfcc=12, n_fft=1024,
        hop_length=hop_length, win_length=win_length)
    # substract mean from mfcc --> normalize mfcc
    mfcc = mfcc - np.mean(mfcc, axis=1).reshape((-1,1)) 
    # delta feature 1st order and 2nd order
    delta1 = librosa.feature.delta(mfcc, order=1)
    delta2 = librosa.feature.delta(mfcc, order=2)
    # X is 36 x T
    X = np.concatenate([mfcc, delta1, delta2], axis=0) # O^r
    # return T x 36 (transpose of X)
    return X.T # hmmlearn use T x N matrix

In [37]:
all_data = {}
all_labels = {}
for cname in class_names:
    file_paths = [os.path.join("audio",  i) for i in os.listdir(os.path.join('audio')) if i.endswith('.wav')]
    data = [get_mfcc(file_path) for file_path in file_paths]
    all_data[cname] = data
    all_labels[cname] = [class_names.index(cname) for i in range(len(file_paths))]

C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[-1.5258789e-05 -3.0517578e-05  3.0517578e-05 ... -1.5258789e-05
  3.0517578e-05 -6.1035156e-05], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[ 9.1552734e-05 -4.5776367e-05  1.5258789e-05 ...  0.0000000e+00
  1.5258789e-05 -4.5776367e-05], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[-0.03970337 -0.03741455 -0.02973938 ...  0.06051636  0.05873108
  0.05732727], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel

C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[-0.00036621 -0.00061035 -0.00210571 ... -0.00390625 -0.00338745
 -0.00288391], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[ 0.00334167  0.00291443  0.00338745 ...  0.00100708  0.00030518
 -0.00027466], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[ 0.00344849  0.00334167  0.00227356 ... -0.00021362  0.00178528
  0.00257874], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarni

C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[ 4.5776367e-05 -4.5776367e-05 -5.1879883e-04 ... -1.7852783e-03
 -2.0141602e-03 -2.2583008e-03], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[0.00111389 0.00151062 0.00143433 ... 0.00090027 0.00152588 0.00112915], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[ 0.00041199 -0.00062561 -0.00016785 ...  0.00263977  0.00161743
  0.00169373], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: 

C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[0.00057983 0.00157166 0.00186157 ... 0.22492981 0.21994019 0.21334839], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[-0.00152588 -0.00135803 -0.00138855 ... -0.0002594   0.00039673
  0.00111389], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: FutureWarning: Pass y=[-4.8828125e-04  2.5939941e-04  2.2430420e-03 ...  0.0000000e+00
  3.0517578e-05 -3.0517578e-05], sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mfcc = librosa.feature.mfcc(
C:\Users\HP PC\AppData\Local\Temp\ipykernel_16316\2517945724.py:13: 

In [38]:
from sklearn.model_selection import train_test_split

X = {'train': {}, 'test': {}}
y = {'train': {}, 'test': {}}
for cname in class_names:
    x_train, x_test, _, y_test = train_test_split(
        all_data[cname], all_labels[cname], 
        test_size = 0.33, 
        random_state=42
    )
    X['train'][cname] = x_train
    X['test'][cname] = x_test
    y['test'][cname] = y_test

In [39]:
for cname in class_names:
    print(cname,len(X['train'][cname]), len(X['test'][cname]), len(y['test'][cname]))

len 72 36 36
xuong 72 36 36
trai 72 36 36
phai 72 36 36
A 72 36 36
B 72 36 36
nhay 72 36 36
ban 72 36 36


In [40]:
import hmmlearn.hmm as hmm

model = {}
for idx, cname in enumerate(class_names):
    start_prob = np.full(states[idx], 0.0)
    start_prob[0] = 1.0
    trans_matrix = np.full((states[idx], states[idx]), 0.0)
    p = 0.5
    np.fill_diagonal(trans_matrix, p)
    np.fill_diagonal(trans_matrix[0:, 1:], 1 - p)
    trans_matrix[-1, -1] = 1.0
    
    #trans matrix
    print(cname)
    print(trans_matrix) 

    model[cname] = hmm.GaussianHMM(
        n_components=states[idx], 
        verbose=True, 
        n_iter=300, 
        startprob_prior=start_prob, 
        transmat_prior=trans_matrix,
        params='stmc',
        init_params='mc',
        random_state=42
    )

    model[cname].fit(X=np.vstack(X['train'][cname]), lengths=[x.shape[0] for x in X['train'][cname]])

len
[[0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. ]]


         1    -4217418.5525             +nan
         2    -3942494.9351     +274923.6174
         3    -3883766.9322      +58728.0029
         4    -3868054.5034      +15712.4288
         5    -3860900.6162       +7153.8872
         6    -3858150.6560       +2749.9602
         7    -3856790.4364       +1360.2196
         8    -3855939.1814        +851.2550
         9    -3855474.4204        +464.7610
        10    -3855241.2473        +233.1731
        11    -3855090.1392        +151.1081
        12    -3854969.6591        +120.4801
        13    -3854866.7888        +102.8703
        14    -3854772.9044         +93.8844
        15    -3854685.5605         +87.3439
        16    -3854612.9770         +72.5835
        17    -3854559.2278         +53.7492
        18    -3854525.2398         +33.9881
        19    -3854496.6373         +28.6025
        20    -3854469.0250         +27.6123
        21    -3854445.9776         +23.0474
        22    -3854426.7826         +19.1950
        23

xuong
[[0.5 0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.  0.  0.  0.  0.  1. ]]


         1    -4225278.0781             +nan
         2    -3992439.7885     +232838.2897
         3    -3942323.0821      +50116.7064
         4    -3926749.9656      +15573.1165
         5    -3919457.5460       +7292.4196
         6    -3912340.5205       +7117.0255
         7    -3906344.0328       +5996.4877
         8    -3902301.4832       +4042.5496
         9    -3900543.3182       +1758.1651
        10    -3899588.6514        +954.6667
        11    -3898692.2883        +896.3631
        12    -3897589.4386       +1102.8497
        13    -3896543.5970       +1045.8416
        14    -3895635.2691        +908.3279
        15    -3894976.9188        +658.3504
        16    -3894484.3030        +492.6158
        17    -3894102.5307        +381.7723
        18    -3893774.4852        +328.0455
        19    -3893504.2065        +270.2787
        20    -3893288.6539        +215.5525
        21    -3893156.6725        +131.9814
        22    -3893087.5710         +69.1016
        23

trai
[[0.5 0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.  0.  0.  0.  0.  1. ]]


         1    -4225278.0787             +nan
         2    -3992439.7901     +232838.2886
         3    -3942323.0833      +50116.7068
         4    -3926749.9667      +15573.1166
         5    -3919457.5498       +7292.4170
         6    -3912340.5252       +7117.0246
         7    -3906344.0360       +5996.4891
         8    -3902301.4847       +4042.5514
         9    -3900543.3185       +1758.1661
        10    -3899588.6515        +954.6670
        11    -3898692.2882        +896.3633
        12    -3897589.4384       +1102.8498
        13    -3896543.5967       +1045.8416
        14    -3895635.2689        +908.3278
        15    -3894976.9186        +658.3503
        16    -3894484.3029        +492.6157
        17    -3894102.5306        +381.7722
        18    -3893774.4851        +328.0455
        19    -3893504.2064        +270.2787
        20    -3893288.6539        +215.5525
        21    -3893156.6725        +131.9814
        22    -3893087.5710         +69.1016
        23

phai
[[0.5 0.5 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.5 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.5 0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.5 0.5 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.  0.  0.  0.  0.  1. ]]


         1    -4225278.0779             +nan
         2    -3992439.7899     +232838.2880
         3    -3942323.0828      +50116.7071
         4    -3926749.9653      +15573.1175
         5    -3919457.5438       +7292.4215
         6    -3912340.5177       +7117.0261
         7    -3906344.0308       +5996.4868
         8    -3902301.4824       +4042.5485
         9    -3900543.3179       +1758.1644
        10    -3899588.6513        +954.6666
        11    -3898692.2884        +896.3630
        12    -3897589.4388       +1102.8496
        13    -3896543.5974       +1045.8414
        14    -3895635.2694        +908.3279
        15    -3894976.9190        +658.3505
        16    -3894484.3031        +492.6158
        17    -3894102.5308        +381.7723
        18    -3893774.4853        +328.0455
        19    -3893504.2066        +270.2787
        20    -3893288.6540        +215.5526
        21    -3893156.6726        +131.9814
        22    -3893087.5710         +69.1016
        23

A
[[0.5 0.5 0.  0.  0.  0. ]
 [0.  0.5 0.5 0.  0.  0. ]
 [0.  0.  0.5 0.5 0.  0. ]
 [0.  0.  0.  0.5 0.5 0. ]
 [0.  0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.  0.  1. ]]


         1    -4237803.2268             +nan
         2    -4073362.8943     +164440.3325
         3    -4049991.2943      +23371.6000
         4    -4022699.5255      +27291.7689
         5    -3996134.0828      +26565.4427
         6    -3982923.9111      +13210.1717
         7    -3976701.5045       +6222.4066
         8    -3973431.5743       +3269.9302
         9    -3971734.5478       +1697.0265
        10    -3970711.7843       +1022.7635
        11    -3969988.4597        +723.3246
        12    -3969399.5445        +588.9153
        13    -3968940.1365        +459.4080
        14    -3968576.7133        +363.4232
        15    -3968304.4672        +272.2460
        16    -3968116.0494        +188.4179
        17    -3967977.7957        +138.2536
        18    -3967876.6852        +101.1105
        19    -3967797.4866         +79.1987
        20    -3967729.0066         +68.4799
        21    -3967669.8642         +59.1424
        22    -3967618.6335         +51.2307
        23

IndexError: list index out of range